### ISSUE TITLE
Polish the Documentation Website

### ISSUE THREAD

**Issue by AaronHeee** [McAuley-Lab/RecWizard#17]
# Task Description

Polish the documentation to make it complete and clean.

# Steps:

- [ ] Rename all the name from `RecBOT` to `RecWizard`;
- [ ] Rename all the `Model Levels` as `Pipeline Levels`;
- [ ] Re-organize APIs reference:
    - [ ] Base, Modules, Pipelines;
    - [ ] Check if they are correct;
- [ ] Complete Developer Guide:
    - [ ] Build a real example in `example/` folder;
    - [ ] New Modules, New Pipelines and New Datasets;
- [ ] Complete the interactive interface doc;
- [ ] Make the documentation website live.
